### ISSUE TITLE
Cannot retrieve listOfLayouts from LayoutModelPlugin

### ISSUE THREAD

**Issue by haleyyew** [haleyyew/SBML2SBGNML#1]
I'm trying to read a SBML file and create a Model. I called SBMLDocument.getModel() and I was able to successfully retrieve the Model. This SBML example file contains layout, and by using JSBMLvisualizer(SBMLDocument) I was able to visualize the SBMLDocument as a JTree. I confirmed that the JTree contains a listOfLayouts and has the glyphs of the layout. 

However, I'm currently stuck at retrieving layout information from the SBMLDocument. I know that the Model does not contain a listOfLayouts, but this must exist somewhere in the Model. Here's what I tried:
(in line 120 of SBML2SBGNML_temp.java) I created a LayoutModelPlugin by calling new LayoutModelPlugin(Model). But it seems LayoutModelPlugin did not store anything into its listOfLayouts (because getLayoutCount() returns 0). 

I was debug and looked at AbstractTreeNode.firePropertyChange, and was overwhelmed. I'm wondering if I'm looking at the right classes to retrieve listOfLayouts.

Thanks.

**Comment by niko-rodrigue** [comment]
Yes, you are looking at the right things. What you need to discover is how the SBML L3 package extends SBML core and how it was implemented in JSBML/LibSBML.

Each SBML core that is extended by a package will have a 'plugin' for this package, like the LayoutModelPlugin for the Model element and the layout package. The way to access the plugins object for the Model element (or any other SBase) is to use the xxPlugin and/or xxExtension methods.

For example, you can call model.isSetPlugin() to know if the plugin exist already. Then, if it exist, you can call model.getPlugin('layout') to get the initialized LayoutModelPlugin.

As an additional excersise, can you tell me looking at the API documentation what is the difference between model.getExtension('layout') and model.getPlugin('layout') ?
